# ---- Stage 1: Build --------------------------------------------------------
FROM golang:1.22-alpine AS builder

RUN apk --no-cache add ca-certificates git tzdata

WORKDIR /app

# Copy dependency manifest first for better layer caching.
# go.sum is generated by the tidy step below if absent.
COPY go.mod go.sum* ./
RUN go mod download

# Copy full source and build a statically-linked binary.
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -o /app/server ./cmd/server

# ---- Stage 2: Runtime -------------------------------------------------------
FROM alpine:3.19

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

COPY --from=builder /app/server .

# Expose webhook listener port (default :9000, override with APP_PORT env var)
EXPOSE 9000

ENTRYPOINT ["/app/server"]
